HKEY_FILE_PATH_A_POS = 1
HKEY_FILE_PATH_B_POS = 2
HKEY_FILE_PATH_A = "data/A.txt"
HKEY_FILE_PATH_B = "data/B.txt"
HKEY_FILE_PATH_MATCHES = "data/matches.txt"

HKEY_TEST_BEG_RANGE = 0
HKEY_TEST_END_RANGE = 50
HKEY_TEST_POINT_QUANTITY = 100
